name: CS102 Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.26.4 scipy scikit-learn nltk surprise pandas
    - name: Run unittests
      run: |
        python -m unittest discover ${{ github.head_ref }}
